version: '3.1'

services:
  mysql:

    image: mysql:5.7.29
    container_name: some_mysql
    restart: unless-stopped

    volumes:
        - ./mysql/data:/var/lib/mysql
        - ./mysql/init:/docker-entrypoint-initdb.d

    ports:
        - 3306:3306

    environment:
        MYSQL_DATABASE: some_mysql
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
    networks: 
        - default