services:
  php:
    image: hiworks/develop-api:7.4
    container_name: php
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:80"
    networks:
      - app-network

  master:
    container_name: master_DB
    image: mysql:5.6
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    volumes:
      - ./dbsetting:/etc/mysql/mysql.conf.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: admin
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "8001:3306"
    networks:
      - app-network

  sub:
    container_name: sub_DB
    image: mysql:5.6
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    volumes:
      - ./dbsetting:/etc/mysql/mysql.conf.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "8002:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge